version: '3.7'

# uncomment below code on efk stack usages [3-1]
# x-logging:
#   &otc-logging
#   driver: fluentd
#   options:
#     fluentd-address: fluentd.host:24224
#     fluentd-async-connect: 'true'
#     mode: non-blocking
#     max-buffer-size: 10m
#     tag: "otc.{{.Name}}"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: api
    ports:
      - '4000:3000'
    command: pnpm run dev
